// Song specification generated by the agent
export interface SongSpec {
  title: string;
  mood: string;
  genre: string;
  bpmRange: {
    min: number;
    max: number;
  };
  chorusLine?: string;
  lengthMs: number;
  forceInstrumental: boolean;
  dayDescription: string;
}

// Result from ElevenLabs music generation
export interface SongResult {
  audioUrl: string;
  title: string;
  promptUsed: string;
  durationMs: number;
  mood: string;
  genre: string;
  wasPromptModified: boolean;
}

// Tool states for UI rendering
export type ToolState = 
  | 'streaming'
  | 'approval-requested' 
  | 'approved'
  | 'output-available'
  | 'error';

